### PR TITLE
bugfix, misc: Adding missing dependencies and future needed ones

### PR DESCRIPTION
**Pull request by JuLieAlgebra**
Not entirely sure why the CI failed on merge to main -- I can't reproduce those errors locally. But there are definitely missing dependencies, which I didn't catch in some of the last closed out PR's. Added the netcdf related dependencies and some common ones I think we'll use in the future.

### CODE REVIEW

**Comment by JuLieAlgebra** [comment]
Oof. I am not sure why it's failing -- Retrigging past workflows that succeeded result in the run failing, which hints that maybe this isn't an issue with our work...? 

Things tried:
- removing the cache
- regenerating the lock file
- adding missing dependencies
- upgrade pixi version

And still can't reproduce locally!

**Comment by JuLieAlgebra** [comment]
Ok, problem seems to be resolved -- I think that the issue was likely the existing cache! Only in the last two commits did the cache get re-written. I'll squash the commits and write a summary of the changes (which should get merged to main)

**Comment by JuLieAlgebra** [comment]
Changes:
- adding missing dependencies
- upgrade pixi version
- upgrade pixi setup workflow version
- change cache to only be written on push to main

**Review by SooluThomas — APPROVED** [review]
Thank you so much for fixing this

**Pull request merged**
